// react-router.config.ts
import { resolve } from "node:path";
import type { Config } from "@react-router/dev/config";
import { scanArticles } from "./src/lib/content-index";

export default {
  ssr: false,
  // Prerender manifest is generated by scanning content/files (spec §3, anti-
  // forgetting rule). The fixed routes /files /lab /about join when P3 lands
  // their route modules; /files/:slug paths here come from published case files.
  prerender: async () => {
    const articles = await scanArticles(resolve(process.cwd(), "content/files"));
    return [
      "/",
      "/files",
      ...articles
        .filter((article) => !article.frontmatter.draft)
        .map((article) => `/files/${article.slug}`),
    ];
  },
} satisfies Config;
