declare module "virtual:magpie-case-files" {
  // Generated by the magpie-case-file Vite plugin: slug -> reading minutes,
  // computed once by the build-side scanner (src/lib/content-index.ts).
  export const caseFileReadingTime: Record<string, number>;
}
